<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\Notification.Core\Notification.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.2.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.2.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
